#+TITLE: Nicholas M George
#+DATE: 2020-06-06
#+OPTIONS: toc:nil author:nil title:nil date:nil num:nil ^:{} \n:1 todo:nil

#+PROPERTY: header-args :eval never-export

#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \usepackage{fontawesome}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \usepackage[round]{natbib}
#+LATEX_HEADER: \hypersetup{colorlinks=true,citecolor=black,linkcolor=black,urlcolor=blue,linkbordercolor=blue,pdfborderstyle={/S/U/W 1}}
#+LATEX_HEADER: \renewcommand{\bibsection}
#+LATEX: \titleformat{\section}{\normalfont\Large\bfseries}{\thesection}{2em}{}[{\titlerule[1.5pt]}]
#+LATEX: \pagestyle{fancy}
#+LATEX: \fancyhf{}
#+LATEX: \cfoot{NM George \thepage}
#+LATEX: \renewcommand{\headrulewidth}{0pt}
#+LATEX: \renewcommand{\footrulewidth}{0pt}
#+LATEX: \sffamily


#+LATEX: \noindent\huge{\bf Nicholas M George}}\\\hfill
#+LATEX: \large{University of Colorado Anschutz Medical Campus}\\
#+LATEX: \large{Cell and Developmental Biology}\\\hfill
#+LATEX: \faEnvelope \: \href{mailto:nicholas.m.george@cuanschutz.edu}{nicholas.m.george@cuanschutz.edu}\\\hfill
#+LATEX: \faGlobe \: \href{https://nickgeorge.net}{https://nickgeorge.net}\\\hfill

#+LATEX: \setlength{\tabcolsep}{12pt}
#+LATEX: \renewcommand{\arraystretch}{1.5}
* Education
:PROPERTIES:
:CUSTOM_ID: education
:END:

\begin{tabular}{lp{0.8\textwidth}}

2016-& \textbf{Ph.D. Neuroscience} \newline 
University of Colorado, Anschutz Medical Campus, Aurora, CO \newline 
Thesis: "Excitable axonal domains adapt to olfactory sensory experience in adults"\newline 
Advisors: Diego Restrepo and Wendy Macklin\\

2014-2016& \textbf{M.S. Anatomy and Neurobiology} \newline 
Virginia Commonwealth University, School of Medicine, Richmond, VA \newline 
Thesis: \href{https://scholarscompass.vcu.edu/etd/4186/}{"Resolution of Inflammation Rescues Axon Initial Segment Disruption"}\newline
Advisor: Jeffrey Dupree\\

2009-2012& \textbf{B.S. Human Nutrition, Foods, and Exercise} \newline 
Virginia Tech, Blacksburg, VA

\end{tabular}

* Funding
:PROPERTIES:
:CUSTOM_ID: funding
:END:

\begin{tabular}{lp{0.8\textwidth}}
2019-2022& \href{https://projectreporter.nih.gov/project_info_details.cfm?aid=9909888&icde=50328886&ddparam=&ddvalue=&ddsub=&cr=1&csb=default&cs=ASC&pball=}{1F31 DC018459-01} \newline NIH/NIDCD \newline "Investigating axonal and glial adaptations to sensory manipulations in the olfactory system" \newline Role: PI \\
2017-2018& TL1 TR001082 \newline Colorado Clinical and Translational Sciences Institute \newline "Neuronavigation with a fiber-coupled microscope"\newline Role: Pre-doctoral Fellow
\end{tabular}

* Publications
:PROPERTIES:
:CUSTOM_ID: publications
:END:

\begin{tabular}{lp{0.8\textwidth}}
2018& Gould, E. A., Busquet, N., Shepherd, D., Dietz, R. M., Herson, P. S., de Souza, F. M. S., Li, A., \textbf{George, N. M.}, Restrepo, D., and Macklin, W. B. (2018). Mild myelin disruption elicits early alteration in behavior and proliferation in the subventricular zone. \textit{eLife}, 7:e34783.\\

2017& Benusa, S. D., \textbf{George, N. M.}, Sword, B. A., DeVries, G. H., and Dupree, J. L. (2017). Acute neuroinflammation induces AIS structural plasticity in a NOX2-dependent manner. \textit{Journal of Neuroinflammation}, 14(1):116.\\
\end{tabular}
* Invited Talks
:PROPERTIES:
:CUSTOM_ID: invited-talks
:END:

\begin{tabular}{lp{0.8\textwidth}}

2019& \textbf{Gordon Research Seminar: Glial Biology}, Ventura, CA \newline "Investigating glial and axonal adaptations to sensory deprivation in the olfactory system"\newline
\textbf{CU Anschutz Neuroscience retreat}, Keystone, CO \newline "Glial and axonal adaptations to sensory deprivation in the olfactory system" \\
2018& \textbf{Translational Science}, Washington, DC \newline "A novel multiphoton microscopy method for neuronavigation in deep brain stimulation surgery"
 \newline \textbf{All Neurosurgery Research Meeting}, Aurora, CO \newline "Characterizing autofluorescence in human STN for deep brain neuronavigation"\\
\end{tabular}
* Poster Presentations
:PROPERTIES:
:CUSTOM_ID: poster-presentations
:END:

\begin{tabular}{lp{0.8\textwidth}}
2020& Association for Chemoreceptive Science, Remote\\
2019& Gordon Research Conference: Glial Biology, Ventura, CA\newline Association for Chemoreceptive Science, Bonita Springs, FL\newline Rocky Mountain Regional Neuroscience Group, Aurora, CO\\
2018& Translational Science, Washington, DC\\
2017& CU Anschutz Neuroscience Retreat, Estes Park, CO\\
2016& William and Mary Graduate Research Symposium, Williamsburg, VA
\end{tabular}
* Honors and Awards
:PROPERTIES:
:CUSTOM_ID: honors-awards
:END:

\begin{tabular}{lp{0.8\textwidth}}
2018& Wellcome Fund Trainee Travel Award for Clinical and Translational Research Conference, Washington, DC\\
2016& Visiting Scholar Award for Excellence in the Natural and Computational Sciences. Poster and research summary presented at The William and Mary Graduate Research Symposium, Williamsburg, VA \\
2015& Poster presentation award at the Virginia Symposium on Brain Immunology and Glia, Richmond, VA
\end{tabular}
* Software Development
:PROPERTIES:
:CUSTOM_ID: software-development
:END:
\begin{tabular}{lp{0.8\textwidth}}
Lab-utility-plugins& I built several small tools and scripts to help lab members and myself simplify common microscopy image analysis tasks such as blinding images and image conversions/manipulations. The source and documentation for these tools are \href{https://github.com/Macklin-Lab/imagej-microscopy-scripts}{freely available} and they are distributed via the Fiji update site \href{https://imagej.github.io/list-of-update-sites/}{Lab-utility-plugins}.\\
ABF Explorer& \href{https://github.com/nkicg6/ABF_Explorer}{ABF Explorer} is a simple GUI to allow for fast visualization of Axon Binary Format (ABF) electrophsiology data and metadata. ABF Explorer is written with python using PyQt and pyqtgraph for interactive graphics, while ABF parsing is done with the \href{https://github.com/swharden/pyABF}{pyABF} library.\\
Website& I built my personal \href{https://nickgeorge.net}{website} using Clojure, a functional lisp which runs on the JVM. I write about programming and science on my website.\\
\end{tabular}
* Other Skills, Experience, and Outreach
:PROPERTIES:
:CUSTOM_ID: other-skills-experience-outreach
:END:
\begin{tabular}{lp{0.8\textwidth}}
2020-& \textbf{Software Carpentry Instructor Training} \newline I attended a \href{https://software-carpentry.org/}{Software Carpentry} workshop when I first started my Ph.D. and it helped me tremendously with data analysis and organization. I recently attended instructor training so that I could lead Software Carpentry seminars to help other researchers adopt techniques to improve experimental data gathering and analysis.\\
2017-2018& \textbf{CU Neuroscience Outreach}\newline
I was involved with the CU Neuroscience outreach program. We organized a yearly outreach event for pre-kindergarten to high school students at the Denver Science museum, featuring interactive demos illustrating how sensory systems and neurons worked. I wrote a simple RaspberryPi application with a Tkinter GUI interface to control a thermal camera and email photos of the students to demonstrate snake "heat vision". The project was called \href{https://github.com/nkicg6/thermalsnap}{SnakeSnap}.\\
2016-2018& \textbf{CU Anschutz Reproducible Research Network} \newline Co-founded the \href{https://ucd-reproducible-research-clinic.github.io/members.html}{CU Anschutz Reproducible Research Network}\newline This was a short-lived organization meant to provide tutorials and resources to help other researchers with data analysis and statistical computing needs. The RRN was set up in a bi-weekly "clinic" setting, where we would give a short presentation on a reproducible research tool (mostly in the R programming language ecosystem) and would then host office hours for researchers. Initially this was a popular event, but became difficult to maintain early in my PhD work.\\
\end{tabular}
